In [ ]:
import numpy as np
arr = np.zeros((3, 3, 2))

print(arr)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
arr[0][0] = 1
arr[0][1] = 2

arr[1][0] = 3
arr[1][1] = 4

arr[2][0] = 5
arr[2][1] = 6

In [ ]:
print(arr)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
rows = 3
cols = 2

for i in range(rows):
  for j in range(cols):
    x = input()
    arr[i][j] = float(x)

1
2
3
4
5
6


In [ ]:
print(arr)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
def add_row(arr_2d, specific_row, no_of_cols):
  sum = 0
  for j in range (no_of_cols):
    sum += arr_2d[specific_row][j]

  return sum 

In [ ]:
print(add_row(arr, 1, 2))

7.0


In [ ]:
import numpy as np
arr = np.zeros((3, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr[0][0] = 1
arr[0][1] = 2
arr[0][2] = 3

arr[1][0] = 4
arr[1][1] = 5
arr[1][2] = 6

arr[2][0] = 7
arr[2][1] = 8
arr[2][2] = 9

print(arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
def find_trace(arr, dim):
  # rows = dim
  # cols = dim
  trace = 0
  for i in range (dim):
    for j in range(dim):
      if i==j:
        trace += arr[i][j]
  
  return trace

In [ ]:
def find_trace(arr, dim):
  # rows = dim
  # cols = dim
  trace = 0
  for i in range (dim):
        trace += arr[i][i]
        
  return trace

In [ ]:
def right_shift(arr, index):
  ////
  ////
  ///
  

In [ ]:
def discardCards(cards, elem):
  for i in range(len(cards)):
    if cards[i] == elem:
      cards = right_shift(cards, i)
      

In [ ]:
import numpy as np
arr = np.zeros((3, 2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
arr[0][0] = 1
arr[0][1] = 2

arr[1][0] = 3
arr[1][1] = 4

arr[2][0] = 5
arr[2][1] = 6

In [ ]:
print(arr)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
rows = 3
cols = 2

for i in range(rows):
  for j in range(cols):
    x = input()
    arr[i][j] = float(x)


1
2
3
4
5
6


In [ ]:
print(arr)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
def row_sum(arr, specific_row, no_of_cols):
  sum = 0
  for j in range(no_of_cols):
    sum += arr[specific_row][j]
  
  return sum

In [ ]:
import numpy as np
arr = np.zeros((3, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr[0][0] = 1
arr[0][1] = 2
arr[0][2] = 3

arr[1][0] = 4
arr[1][1] = 5
arr[1][2] = 6

arr[2][0] = 7
arr[2][1] = 8
arr[2][2] = 9

print(arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
def find_trace(arr, rows, cols):
  trace = 0

  for i in range(rows):
    for j in range(cols):
      if i==j:
        trace += arr[i][j]

  return trace

In [ ]:
print(find_trace(arr, 3, 3))

15.0


In [ ]:
def find_trace(arr, dims):
  trace = 0

  for i in range(dims):
        trace += arr[i][i]

  return trace

In [ ]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix   
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
     
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
 
# iterating by row of A
for i in range(len(A)):
 
    # iterating by column by B
    for j in range(len(B[0])):
 
        # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
 
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [ ]:
 if len(A[0]) != len(B):
      print("Invalid matrix dimensions")

In [ ]:
for i in rows of A:
  for j in cols of B:
    result[i][j] = ith row of A . jth col of B

In [ ]:
# A = row1 * col1 
# B = row2 * col2 

def matrix_multiplication(A, B, row1, col1, row2, col2):
  result = np.zeros(row1, col2)

  if col1 != row2:
    return "Invalid Dimensions"

  for i in range(row1):
    for j in range(col2):
      for k in range(col1): #row2
        result[i][j] += A[i][k] * B[k][j]

  return result


In [ ]:
# A = row1 * col1 
# B = row2 * col2 
import numpy as np
def matrix_multiplication(A, B):
  row1 = len(A)
  col1 = len(A[0])
  row2 = len(B)
  col2 = len(B[0])

  if col1 != row2:
    return "invalid dimensions"

  C = np.zeros((row1, col2))

  for i in range(row1):
    for j in range(col2):
      #####c[i][j] = row i . col j####
      for k in range(col1): #row2
        C[i][j] += A[i][k] * B[k][j]

  return C

In [ ]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix   
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]



In [ ]:
print(matrix_multiplication(A, B))

[[114. 160.  60.  27.]
 [ 74.  97.  73.  14.]
 [119. 157. 112.  23.]]


10
20
30
40
50
