**Instructions to Follow (Failing to follow these will result mark penalties).**


1.   You can not use any built-in function except len()
2.   You can use the shape tuple of numpy arrays
2.   You can not use any other python collections except array (e.g: tuptle, dictionaries etc.). 
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.zeros((10), dtype = int) #Initializing an array length 10 with values 0

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.






In [1]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [2]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))



In [5]:
lst = [1, 2, 3, 4]
arr = np.array(lst)
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [8]:
arr2 = np.zeros(6)
arr3 = np.zeros(6, dtype = int)
print(arr2)
print(arr3)

[0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0]


In [21]:
marray = np.array([[1, 7, 8], [9, 3, 2], [4, 6, 8]])
print(marray)
print(marray[1][1])
print(marray.shape)

[[1 7 8]
 [9 3 2]
 [4 6 8]]
3
(3, 3)


In [20]:
marray_zero = np.zeros((3, 3, 4))
marray_zero[1][1][2] = 4
print(marray_zero)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 4. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [26]:
marray = np.array([[1, 7, 8, 9], [9, 3, 2, 8], [4, 6, 8, 9]])


row, col = marray.shape

for i in range(row):
  for j in range(col):
    print("|", marray[i][j], "|", end = " ")
  print()

| 1 | | 7 | | 8 | | 9 | 
| 9 | | 3 | | 2 | | 8 | 
| 4 | | 6 | | 8 | | 9 | 


Task 1: Zigzag Walk

In [41]:
def walk_zigzag(floor):
  row, col = floor.shape
  for i in range(row):
    if i%2 == 0:
      for j in range(0, col, 2):
         print(floor[i][j], end = " ")
    else:
      for k in range(col-1, 0, -2):
        print(floor[i][k], end= " ")
    print()




floor = np.array([[ '3W' , '8B' , '4W' , '6B' , '1W' , '5B'],['3B' , '2W' , '1B' , '6W' , '3B' , '8W'],
                  ['9W' , '0B' , '7W' , '5B' , '3W' , '8B'],['2B' , '1W' , '3B' , '6W' , '0B' , '4W'],
                   ['1W' , '4B' , '2W' , '8B' , '6W' , '6B']])
print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3W 4W 1W 
# 8W 6W 2W 
# 9W 7W 3W 
# 4W 6W 1W 
# 1W 2W 6W


|  3W |  8B |  4W |  6B |  1W |  5B |
-------------------------------------
|  3B |  2W |  1B |  6W |  3B |  8W |
-------------------------------------
|  9W |  0B |  7W |  5B |  3W |  8B |
-------------------------------------
|  2B |  1W |  3B |  6W |  0B |  4W |
-------------------------------------
|  1W |  4B |  2W |  8B |  6W |  6B |
-------------------------------------
Walking Sequence:
3W 4W 1W 
8W 6W 2W 
9W 7W 3W 
4W 6W 1W 
1W 2W 6W 


Task 2: Landscape Screen

In [49]:
def landscape(m):
  row, col = m.shape
  new_array = np.zeros((col, row), dtype= int)
  for i in range(row):
    for j in range(col):
      new_array[j][i] = m[i][j]
  return new_array
  


m = np.random.randint(15,size=(4,3)) #This creates an np array of 4 x 3 where the values are random numbers from [0,15) range
print_matrix(m)
print()
print_matrix(landscape(m))

|  7  |  3  |  14 |
-------------------
|  4  |  10 |  11 |
-------------------
|  6  |  5  |  6  |
-------------------
|  13 |  10 |  10 |
-------------------

|  7  |  4  |  6  |  13 |
-------------------------
|  3  |  10 |  5  |  10 |
-------------------------
|  14 |  11 |  6  |  10 |
-------------------------


Task 3: Seating Arrangement

In [92]:
import numpy as np
def arrangement(m, diff):
  row, col = m.shape
  flag = False
  for i in range(0, row):
    for j in range(0, col):
      if i != j:
        if m[j][i] - m[i][j] == diff or m[i][j] - m[j][i]==diff:
          flag = True
        else:
          return False

  return flag


m = np.array([[7,13,9,14],[12,8,15,11],[10,17,3,2],[15,10,1,4]])
print_matrix(m)
print()
returned_value = arrangement(m,1)
print(returned_value)#This should print False
unittest.output_test(returned_value, False)

m = np.array([[8,15,7,12],[13,2,18,11],[9,20,5,2],[14,9,0,10]])
print_matrix(m)
print()
returned_value = arrangement(m,2)
print(returned_value)#This should print True
unittest.output_test(returned_value, True)

|  7  |  13 |  9  |  14 |
-------------------------
|  12 |  8  |  15 |  11 |
-------------------------
|  10 |  17 |  3  |  2  |
-------------------------
|  15 |  10 |  1  |  4  |
-------------------------

False
Accepted
|  8  |  15 |  7  |  12 |
-------------------------
|  13 |  2  |  18 |  11 |
-------------------------
|  9  |  20 |  5  |  2  |
-------------------------
|  14 |  9  |  0  |  10 |
-------------------------

True
Accepted


Task 4: Chess Piece

In [93]:
def show_knight_move(knight):
  row,col=knight[0],knight[1]
  arr=np.zeros((8,8),dtype=int)
  arr[knight[0]][knight[1]]=33
  pos= np.array([ (1,2),(-1,2),(1,-2),(-1,-2),(-2,1),(-2,-1),(2,1),(2,-1)])
  for i in pos:
    if (0<=row+i[0]<=7) and (0<=col+i[1]<=7):
      arr[row+i[0]][col+i[1]]=3
  return arr

knight = (3,4)
chess_board = show_knight_move(knight)
print_matrix(chess_board)

|  0  |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
-------------------------------------------------
|  0  |  0  |  0  |  3  |  0  |  3  |  0  |  0  |
-------------------------------------------------
|  0  |  0  |  3  |  0  |  0  |  0  |  3  |  0  |
-------------------------------------------------
|  0  |  0  |  0  |  0  |  33 |  0  |  0  |  0  |
-------------------------------------------------
|  0  |  0  |  3  |  0  |  0  |  0  |  3  |  0  |
-------------------------------------------------
|  0  |  0  |  0  |  3  |  0  |  3  |  0  |  0  |
-------------------------------------------------
|  0  |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
-------------------------------------------------
|  0  |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
-------------------------------------------------


Bonus Task (UNGRADED)

In [ ]:
def topple(knight,rook):
  #To Do
  return None


knight = (5,6)
rook = (5,1)
chess_board, ans = topple(knight,rook)
print_matrix(chess_board)
print(ans) #This should print Rook can kill