In [8]:
import numpy as np
arr = np.zeros((3, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
arr[0][0] = 1
arr[0][1] = 2
arr[0][2] = 3
arr[1][0] = 4
arr[1][1] = 5
arr[1][2] = 6
arr[2][0] = 7
arr[2][1] = 8
arr[2][2] = 9
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [14]:
row = 2
col = 3

for i in range(row):
  for j in range(col):
    x = input()
    arr[i][j] = float(x)
print(arr)

1
2
3
4
5
6
[[1. 2. 3.]
 [4. 5. 6.]
 [0. 0. 0.]]


In [18]:
def sum_of_1_row(arr, row, no_of_cols):
  sum = 0
  for i in range(no_of_cols):
    sum += arr[row][i]
  return sum
print(sum_of_1_row(arr, 1, 3))

15.0


In [21]:
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [23]:
def find_trace(arr, dim):
  trace = 0
  for i in range(dim):
    trace += arr[i][i]
  return trace

print(find_trace(arr, 3))

15.0
