In [24]:
import numpy as np
def print_result(flag,a,b):
  print("The sum of the each row:",a)
  print("The sum of the each column:",b)
  print("_________________________")
  if flag:
    print("****valid******")
  else:
    print("****invalid******")
  print("_________________________")

def Balance(arr):
  row, col = arr.shape
  rowsum = 0
  colsum = 0
  row_sum= [None] * col
  col_sum= [None] * col

  for i in range(row):
    for j in range(col):
      rowsum += arr[i][j]
      row_sum[j] = rowsum
      break


  for k in range(col):
    for l in range(row):
      colsum += arr[k][l]
      col_sum[l] = colsum
      break




  flag = True ## Denote True as balanced and False for unbalanced

  ##your code

  return flag,row_sum,col_sum




###DRIVER CODE
##TEST1
arr= np.array([[3,-9,7,0],
              [3,7,-1,6],
              [4,19,2,0],
              [0,7,-3,4]])
print("TEST CASE 1:", arr,sep="\n")
output_boolean,row_sum,col_sum = Balance(arr)
print_result(output_boolean,row_sum,col_sum)

##TEST2
arr= np.array([[1,2,7,0],
               [3,5,2,6],
               [4,2,0,0],
               [2,7,-3,4]])

print("TEST CASE 2:", arr,sep="\n")
output_boolean,row_sum,col_sum = Balance(arr)
print_result(output_boolean,row_sum,col_sum)

##TEST3
arr= np.array([[3,2,7,0],
               [3,7,2,6],
               [4,2,2,0],
              [2,7,-3,6]])
print("TEST CASE 3:", arr,sep="\n")
output_boolean,row_sum,col_sum = Balance(arr)
print_result(output_boolean,row_sum,col_sum)

TEST CASE 1:
[[ 3 -9  7  0]
 [ 3  7 -1  6]
 [ 4 19  2  0]
 [ 0  7 -3  4]]
The sum of the each row: [10, None, None, None]
The sum of the each column: [10, None, None, None]
_________________________
****valid******
_________________________
TEST CASE 2:
[[ 1  2  7  0]
 [ 3  5  2  6]
 [ 4  2  0  0]
 [ 2  7 -3  4]]
The sum of the each row: [10, None, None, None]
The sum of the each column: [10, None, None, None]
_________________________
****valid******
_________________________
TEST CASE 3:
[[ 3  2  7  0]
 [ 3  7  2  6]
 [ 4  2  2  0]
 [ 2  7 -3  6]]
The sum of the each row: [12, None, None, None]
The sum of the each column: [12, None, None, None]
_________________________
****valid******
_________________________
